# Generated by Django 4.0.4 on 2022-04-26 23:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tunning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Tunning date')),
                ('service', models.CharField(choices=[('A', 'OIL & FILTER'), ('B', 'ROTATE TIRES'), ('C', 'TRANSMISSION FLUID'), ('D', 'AIR FILTER'), ('E', 'TIRE PRESSURE AND TREAD DEPTH'), ('F', 'BRAKE, AND PARKING LIGHTS'), ('G', 'SPARK PLUGS'), ('H', 'COOLANT FLUID EXCHANGE')], default='A', max_length=1)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.car')),
            ],
        ),
    ]
