# Generated by Django 4.0.4 on 2022-04-27 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_tunning'),
    ]

    operations = [
        migrations.CreateModel(
            name='Upgrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('details', models.CharField(max_length=250)),
            ],
        ),
        migrations.AddField(
            model_name='car',
            name='upgrades',
            field=models.ManyToManyField(to='main_app.upgrade'),
        ),
    ]
