# Generated by Django 4.0.4 on 2022-04-28 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_upgrade_car_upgrades'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tunning',
            options={'ordering': ['-date']},
        ),
    ]
