# Generated by Django 4.0.4 on 2022-04-28 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_tunning_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tunning',
            name='service',
            field=models.CharField(choices=[('A', 'OIL & FILTER'), ('B', 'ROTATE TIRES'), ('C', 'TRANSMISSION FLUID'), ('D', 'AIR FILTER'), ('E', 'TIRE PRESSURE AND TREAD DEPTH'), ('F', 'BRAKE, AND PARKING LIGHTS'), ('G', 'SPARK PLUGS'), ('H', 'COOLANT FLUID EXCHANGE'), ('I', 'BATTERY SERVICE')], default='A', max_length=1),
        ),
    ]
